### ISSUE TITLE
battery current

### ISSUE THREAD

**Issue by tasiek30** [LibreSolar/ChargeController_Software#6]
Hello

At the beginning i would like to congratulate You. This project is awesome. Very professional design.

I have a question for You. Why the algorithm does not include the load current? I think, battery current should be calculate based on DC/DC current and load current and then run state machine. 

Best regards

**Comment by martinjaeger** [comment]
Sorry for the late reply. This issue should be solved with this commit: 73a205f60f399bdf51d7f18c62fea71b7287ab23

If you disagree, please re-open this issue.
